### ISSUE TITLE
Could not resolve "../../../utils" when running `pnpm run build` in Nuxt 3

### ISSUE THREAD

**Issue by phillipmohr** [nuxt-modules/ngrok#35]
I'm using the following module version `"@nuxtjs/ngrok": "^3.0.1"` and my Nuxt version is`"nuxt": "^3.12.2"` 
I'm getting this error message when running `pnpm run build` in Nuxt 3.

```js
Error:  [nitro] RollupError: Could not resolve "../../../utils" from "node_modules/.pnpm/@nuxtjs+ngrok@3.0.1_magicast@0.3.5_rollup@4.23.0_webpack-sources@3.2.3/node_modules/@nuxtjs/ngrok/dist/runtime/server/plugins/ngrok.mjs"


undefined
Error:  Could not resolve "../../../utils" from "node_modules/.pnpm/@nuxtjs+ngrok@3.0.1_magicast@0.3.5_rollup@4.23.0_webpack-sources@3.2.3/node_modules/@nuxtjs/ngrok/dist/runtime/server/plugins/ngrok.mjs"
  at getRollupError (node_modules/.pnpm/rollup@4.23.0/node_modules/rollup/dist/es/shared/parseAst.js:393:41)
  at error (node_modules/.pnpm/rollup@4.23.0/node_modules/rollup/dist/es/shared/parseAst.js:389:42)
  at ModuleLoader.handleInvalidResolvedId (node_modules/.pnpm/rollup@4.23.0/node_modules/rollup/dist/es/shared/node-entry.js:19329:24)
  at node_modules/.pnpm/rollup@4.23.0/node_modules/rollup/dist/es/shared/node-entry.js:19289:26 

Error:  Could not resolve "../../../utils" from "node_modules/.pnpm/@nuxtjs+ngrok@3.0.1_magicast@0.3.5_rollup@4.23.0_webpack-sources@3.2.3/node_modules/@nuxtjs/ngrok/dist/runtime/server/plugins/ngrok.mjs"
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

Is this a known issue? 

I saw the utils have been moved not long ago. This commit might be related: 
https://github.com/nuxt-modules/ngrok/commit/1f5a3f7422a1171168afa6221cfa492b3b2fdf1a

**Comment by arashsheyda** [comment]
sorry I totally forgot to publish a new version after the fix, will publish a new version after work. thanks so much!

**Comment by phillipmohr** [comment]
> sorry I totally forgot to publish a new version after the fix, will publish a new version after work. thanks so much!

I appreciate the fast reply 🙏  let me know when a new version has been released, thanks!

**Comment by arashsheyda** [comment]
should be fixed on the latest version
